base:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  omni_base_controller:
    type: omni_drive_controller/OmniDriveController
    wheel1: omni_wheel_1_joint
    wheel2: omni_wheel_2_joint
    wheel3: omni_wheel_3_joint
    wheel_separation: 0.282
    wheel_radius: 0.0635
    publish_cmd: false
    publish_wheel_joint_controller_state: false
    publish_rate: 50.0
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    cmd_vel_timeout: 20.0

body:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - body_rotate_joint
      - elevation_joint
#      - arm_base_joint
      - arm1_joint
      - arm2_joint
      - arm3_joint
      - arm4_joint
      - arm5_joint
      - arm6_joint

  body_rotate_controller:
    type: position_controllers/JointPositionController
    joint: body_rotate_joint

  elevation_controller:
    type: position_controllers/JointPositionController
    joint: elevation_joint

  arm_base_controller:
    type: position_controllers/JointPositionController
    joint: arm_base_joint

  arm1_controller:
    type: position_controllers/JointPositionController
    joint: arm1_joint

  arm2_controller:
    type: position_controllers/JointPositionController
    joint: arm2_joint

  arm3_controller:
    type: position_controllers/JointPositionController
    joint: arm3_joint

  arm4_controller:
    type: position_controllers/JointPositionController
    joint: arm4_joint

  arm5_controller:
    type: position_controllers/JointPositionController
    joint: arm5_joint

  arm6_controller:
    type: position_controllers/JointPositionController
    joint: arm6_joint

  gripper_controller:
    type: position_controllers/JointPositionController
    joint: gripper_joint

head:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  screen_tilt_controller:
    type: position_controllers/JointPositionController
    joint: head_screen_tilt_joint

  pan_controller:
    type: position_controllers/JointPositionController
    joint: head_pan_joint

  tilt_controller:
    type: position_controllers/JointPositionController
    joint: head_tilt_joint



# omni_wheel_1_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: omni_wheel_1_joint

# omni_wheel_2_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: omni_wheel_2_joint

# omni_wheel_3_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: omni_wheel_3_joint

# arm_controller:
#   type: position_controllers/JointTrajectoryController
#   joints:
#     - body_rotate_joint
#     - trans_module_elv_joint
#     - arm_base_joint
#     - arm_joint1
#     - arm_joint2
#     - arm_joint3
#     - arm_joint4
#     - arm_joint5
#     - arm_joint6

# head_pan_controller:
#   type: position_controllers/JointPositionController
#   joint: head_pan_joint

# head_screen_tilt_controller:
#   type: position_controllers/JointPositionController
#   joint: head_screen_tilt_joint

# head_tilt_unit_controller:
#   type: position_controllers/JointPositionController
#   joint: head_tilt_unit_joint




